### ISSUE TITLE
Display image capture on survey page

### ISSUE THREAD

**Issue by uncleserb** [AskiaADX/Camera#3]
Currently when a respondent captures / selects a photo to upload, there is no visual feedback at all that the resource selection; e.g we should display the photo capture directly in the survey page.
Should be a rather simple JavaScript snippet as you can see [here](https://codepen.io/codepo8/pen/gOpjZmr).

**Comment by j4t1nb** [comment]
Cheers Paul - I've added this to the backlog: https://askia.atlassian.net/browse/ASKIA-590

**Comment by uncleserb** [comment]
Great! Thanks @j4t1nb; will close here as it's now a duplicate ;)
